# Generated by Django 5.2.7 on 2025-11-27 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='max_attempts',
        ),
    ]
