# Generated by Django 5.2.7 on 2025-11-27 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp_service', '0002_remove_otp_max_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='attempts',
        ),
    ]
