# Generated by Django 5.2.7 on 2025-11-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_service', '0003_remove_otp_attempts'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['order_id', 'status', 'otp_code'], name='otps_order_i_1cd18e_idx'),
        ),
    ]
