# Generated by Django 5.2.7 on 2025-11-28 01:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_activitylog_module'),
        ('order_processing', '0002_initial'),
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_version', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debit_account', models.CharField(max_length=50)),
                ('credit_account', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('reference_type', models.CharField(choices=[('PAYMENT_RECEIVED', 'Payment Received'), ('INVOICE_ALLOCATION', 'Invoice Allocation'), ('REFUND', 'Refund'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('reference_id', models.UUIDField()),
                ('entry_status', models.CharField(choices=[('PENDING', 'Pending'), ('POSTED', 'Posted'), ('VOID', 'Void'), ('REVERSED', 'Reversed')], default='PENDING', max_length=20)),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('value_date', models.DateField(default=django.utils.timezone.now)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('internal_note', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'accounting_entries',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerWallet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_version', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('wallet_type', models.CharField(choices=[('LOYALTY', 'Loyalty'), ('PREPAID', 'Prepaid'), ('CREDIT', 'Credit')], default='LOYALTY', max_length=20)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('is_refundable', models.BooleanField(default=True)),
                ('max_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_wallets',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_version', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='DRAFT', max_length=20)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_version', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('allocation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'payment_allocations',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_version', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method_type', models.CharField(choices=[('CARD', 'Card'), ('MOBILE_MONEY', 'Mobile Money'), ('WALLET', 'Wallet'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash')], max_length=20)),
                ('provider', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=255)),
                ('masked_identifier', models.CharField(max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('provider_details', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment_methods',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_version', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('PAYMENT', 'Payment'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Adjustment'), ('EXPIRY', 'Expiry')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('running_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_type', models.CharField(blank=True, max_length=30, null=True)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='COMPLETED', max_length=20)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'wallet_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_order_i_3d4604_idx',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.AddField(
            model_name='payment',
            name='customer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('MOMO', 'Mobile Money'), ('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('CASH', 'Cash'), ('CRYPTO', 'Cryptocurrency'), ('X_SWIFT_STABLE_COIN', 'X-Swift Stable Coin'), ('WALLET', 'Customer Wallet')], max_length=20),
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_entries', to='payment.payment'),
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurant'),
        ),
        migrations.AddField(
            model_name='customerwallet',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurant'),
        ),
        migrations.AddField(
            model_name='customerwallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='order_processing.offlineorder'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurant'),
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_entries', to='payment.invoice'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='allocated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='payment.invoice'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='payment.payment'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.paymentmethod'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer_user', 'created_at'], name='payments_custome_de2e2c_idx'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payment.customerwallet'),
        ),
        migrations.AddIndex(
            model_name='customerwallet',
            index=models.Index(fields=['user', 'restaurant'], name='customer_wa_user_id_36fc8b_idx'),
        ),
        migrations.AddIndex(
            model_name='customerwallet',
            index=models.Index(fields=['status'], name='customer_wa_status_9b74a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customerwallet',
            unique_together={('user', 'restaurant', 'wallet_type')},
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['order', 'status'], name='invoices_order_i_5ce135_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['restaurant', 'status'], name='invoices_restaur_c666d7_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='invoices_due_dat_039a25_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingentry',
            index=models.Index(fields=['restaurant', 'entry_date'], name='accounting__restaur_ecd99e_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingentry',
            index=models.Index(fields=['reference_type', 'reference_id'], name='accounting__referen_810d46_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingentry',
            index=models.Index(fields=['debit_account', 'credit_account'], name='accounting__debit_a_14fd90_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingentry',
            index=models.Index(fields=['entry_status'], name='accounting__entry_s_e63a11_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['invoice', 'payment'], name='payment_all_invoice_b68c99_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['payment', 'invoice'], name='payment_all_payment_499946_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentallocation',
            unique_together={('invoice', 'payment')},
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['user', 'is_active'], name='payment_met_user_id_a6fdd9_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['method_type'], name='payment_met_method__c0df5d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['token'], name='payment_met_token_56df08_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user', 'is_default'), name='unique_default_per_user'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', 'created_at'], name='wallet_tran_wallet__aa27da_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['reference_type', 'reference_id'], name='wallet_tran_referen_f20c6c_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['transaction_type'], name='wallet_tran_transac_377ecc_idx'),
        ),
    ]
