# Generated by Django 5.2.7 on 2025-11-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_accountingentry_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerwallet',
            name='currency',
            field=models.CharField(default='X-SWIFT', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('MOMO', 'Mobile Money'), ('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('CASH', 'Cash'), ('CRYPTO', 'Cryptocurrency'), ('WALLET', 'Customer Wallet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('CARD', 'Card'), ('MOMO', 'Mobile Money'), ('WALLET', 'Customer Wallet'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('CRYPTO', 'Cryptocurrency')], max_length=20),
        ),
    ]
