# Generated by Django 5.2.7 on 2025-11-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_customerwallet_currency_alter_payment_gateway_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled'), ('AWAITING_COLLECTION', 'Awaiting Collection')], default='PENDING', max_length=20),
        ),
    ]
