# Generated by Django 5.2.7 on 2025-11-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
