# Generated by Django 5.2.7 on 2025-11-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_remove_payment_payment_method_delete_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='metadata',
            field=models.JSONField(null=True),
        ),
    ]
