# Generated by Django 5.2.7 on 2025-12-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_invoice_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingentry',
            name='created_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('PAYMENT', 'Payment'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Adjustment'), ('EXPIRY', 'Expiry'), ('AUTHORIZATION', 'Authorization'), ('CAPTURE', 'Capture'), ('RELEASE', 'Release')], max_length=20),
        ),
    ]
