# Generated by Django 5.2.7 on 2025-12-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_accountingentry_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerwallet',
            name='currency',
            field=models.CharField(default='X-SWIFT', max_length=8),
        ),
    ]
