# Generated by Django 5.2.7 on 2025-11-04 11:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_version', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('local_order_id', models.CharField(max_length=50, unique=True)),
                ('supabase_order_id', models.UUIDField(blank=True, null=True)),
                ('table_id', models.UUIDField(blank=True, null=True)),
                ('customer_id', models.UUIDField(blank=True, null=True)),
                ('order_items', models.JSONField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('special_instructions', models.TextField(blank=True)),
                ('order_status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('sync_status', models.CharField(choices=[('PENDING_SYNC', 'Pending Sync'), ('SYNCING', 'Syncing'), ('SYNCED', 'Synced'), ('SYNC_FAILED', 'Sync Failed'), ('CONFLICT', 'Conflict')], default='PENDING_SYNC', max_length=20)),
                ('estimated_preparation_time', models.IntegerField(blank=True, null=True)),
                ('actual_preparation_time', models.IntegerField(blank=True, null=True)),
                ('preparation_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sync_attempts', models.IntegerField(default=0)),
                ('last_sync_attempt', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'offline_orders',
            },
        ),
        migrations.CreateModel(
            name='OrderCRDTState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_version', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vector_clock', models.JSONField()),
                ('last_operation', models.CharField(max_length=50)),
                ('operation_timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'order_crdt_states',
            },
        ),
    ]
