# Generated by Django 5.2.7 on 2025-11-04 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
        ('order_processing', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineorder',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='payment.payment'),
        ),
        migrations.AddField(
            model_name='offlineorder',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurant'),
        ),
        migrations.AddField(
            model_name='ordercrdtstate',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order_processing.offlineorder'),
        ),
        migrations.AddIndex(
            model_name='offlineorder',
            index=models.Index(fields=['restaurant', 'order_status'], name='offline_ord_restaur_91b7de_idx'),
        ),
        migrations.AddIndex(
            model_name='offlineorder',
            index=models.Index(fields=['restaurant', 'sync_status'], name='offline_ord_restaur_fa288a_idx'),
        ),
        migrations.AddIndex(
            model_name='offlineorder',
            index=models.Index(fields=['local_order_id'], name='offline_ord_local_o_f08dea_idx'),
        ),
        migrations.AddIndex(
            model_name='offlineorder',
            index=models.Index(fields=['created_at'], name='offline_ord_created_cf57b6_idx'),
        ),
    ]
