# Generated by Django 5.2.7 on 2025-11-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_processing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineorder',
            name='metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='offlineorder',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('SYST_RECONCILIATION', 'Sys-Reconciliation')], default='PENDING', max_length=20),
        ),
    ]
