# Generated by Django 5.2.7 on 2025-11-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_processing', '0004_alter_offlineorder_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineorder',
            name='order_type',
            field=models.CharField(choices=[('DINE_IN', 'dine_in'), ('TAKE_AWAY', 'take_away'), ('DELIVERY', 'delivery')], default='DINE_IN', max_length=30),
        ),
        migrations.AlterField(
            model_name='offlineorder',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
