# Generated by Django 5.2.7 on 2025-11-30 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_processing', '0005_offlineorder_order_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offlineorder',
            name='metadata',
        ),
    ]
