# Generated by Django 5.2.7 on 2025-11-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_processing', '0006_remove_offlineorder_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineorder',
            name='order_meta_data',
            field=models.JSONField(null=True),
        ),
    ]
