# Generated by Django 5.2.7 on 2025-11-30 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_processing', '0007_offlineorder_order_meta_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offlineorder',
            old_name='order_meta_data',
            new_name='metadata',
        ),
    ]
