# Generated by Django 5.2.7 on 2025-11-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_processing', '0008_rename_order_meta_data_offlineorder_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlineorder',
            name='order_type',
            field=models.CharField(choices=[('DINE_IN', 'dine_in'), ('TAKE_AWAY', 'take_away'), ('DELIVERY', 'delivery'), ('SYS_RECONCILIATION', 'sys_reconciliation')], default='DINE_IN', max_length=30),
        ),
    ]
