# Generated by Django 5.2.7 on 2025-11-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_processing', '0009_alter_offlineorder_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineorder',
            name='table_number',
            field=models.TextField(blank=True),
        ),
    ]
