# Generated by Django 5.2.7 on 2025-10-22 12:26

import django.contrib.postgres.indexes
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("cloud_api", "0004_create_remaining_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("order", "Order"), ("booking", "Booking")],
                        max_length=20,
                    ),
                ),
                ("reference_id", models.UUIDField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("payment_method", models.CharField(default="momo", max_length=50)),
                ("phone_number", models.CharField(max_length=50)),
                (
                    "momo_transaction_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("gateway_response", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "payments",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["communication_preferences"],
                name="idx_users_communication_prefs",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["idempotency_key"], name="idx_payments_idempotency"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["reference_id"], name="idx_payments_reference"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="idx_payments_status"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["momo_transaction_id"], name="idx_payments_momo_txn"
            ),
        ),
    ]
