# Generated by Django 5.2.7 on 2025-11-04 11:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCache',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_version', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('menu_data', models.JSONField()),
                ('version', models.IntegerField(default=1)),
                ('checksum', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurant')),
            ],
            options={
                'db_table': 'menu_cache',
                'indexes': [models.Index(fields=['restaurant', 'is_active'], name='menu_cache_restaur_3250e3_idx'), models.Index(fields=['checksum'], name='menu_cache_checksu_b90385_idx')],
                'unique_together': {('restaurant', 'version')},
            },
        ),
    ]
