# Generated by Django 5.2.7 on 2025-11-16 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('menu_cache', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucache',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.restaurant'),
        ),
    ]
