# Generated by Django 5.2.7 on 2025-11-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_cache', '0002_alter_menucache_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucache',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        
    ]
