# Generated by Django 5.2.7 on 2025-11-13 06:51

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("cloud_api", "0004_create_remaining_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["communication_preferences"],
                name="idx_users_communication_prefs",
            ),
        ),
    ]
