# Generated by Django 5.2.7 on 2025-11-13 08:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_api", "0006_deliverypartner_restaurantstaff_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitalTicket",
            fields=[
                (
                    "ticket_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("qr_code", models.CharField(max_length=500, unique=True)),
                (
                    "ticket_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("used", "Used"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checked_in_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checked_in_tickets",
                        to="cloud_api.user",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket",
                        to="cloud_api.order",
                    ),
                ),
            ],
            options={
                "db_table": "digital_tickets",
                "indexes": [
                    models.Index(fields=["qr_code"], name="idx_tickets_qr_code"),
                    models.Index(fields=["ticket_status"], name="idx_tickets_status"),
                    models.Index(fields=["expires_at"], name="idx_tickets_expires"),
                ],
            },
        ),
    ]
