# Generated by Django 5.2.8 on 2025-11-15 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_api", "0007_digitalticket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurantstaff",
            name="user_role_id",
        ),
        migrations.AddField(
            model_name="restaurantstaff",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cloud_api.user",
            ),
        ),
        migrations.AlterField(
            model_name="restaurantstaff",
            name="employee_id",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
