# Generated by Django 5.2.8 on 2025-11-15 17:45

from django.db import migrations, models
from django.db import connection


def check_and_delete_restaurant_staff(apps, schema_editor):
    """Only delete RestaurantStaff table if it exists"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_name = 'restaurant_staff'
            );
        """)
        table_exists = cursor.fetchone()[0]
        
        if table_exists:
            cursor.execute("DROP TABLE restaurant_staff CASCADE;")


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_api", "0008_remove_restaurantstaff_user_role_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="menu_items/",
                verbose_name="Item Image",
            ),
        ),
        migrations.RunPython(
            check_and_delete_restaurant_staff,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
