# Generated by Django 5.2.8 on 2025-11-15 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_api", "0009_menuitem_image_delete_restaurantstaff"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RestaurantStaff",
        ),
    ]
