# Generated by Django 5.2.8 on 2025-11-15 19:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_api", "0010_delete_restaurantstaff"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestaurantStaff",
            fields=[
                (
                    "staff_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(max_length=50, null=True, unique=True),
                ),
                ("hire_date", models.DateField(auto_now_add=True)),
                ("termination_date", models.DateField(blank=True, null=True)),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "efficiency_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("total_orders_served", models.IntegerField(default=0)),
                (
                    "average_order_time",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "customer_rating_avg",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("on_leave", "On Leave"),
                            ("terminated", "Terminated"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("managed_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cloud_api.user",
                    ),
                ),
            ],
            options={
                "db_table": "restaurant_staff",
            },
        ),
    ]
