# Generated by Django 5.2.7 on 2025-11-04 11:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component', models.CharField(choices=[('DATABASE', 'Database'), ('REDIS', 'Redis'), ('SUPABASE', 'Supabase'), ('CELERY', 'Celery')], max_length=20)),
                ('is_healthy', models.BooleanField(default=True)),
                ('response_time_ms', models.IntegerField(null=True)),
                ('last_check', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'health_checks',
                'indexes': [models.Index(fields=['component', '-last_check'], name='health_chec_compone_bd2819_idx')],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_version', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supabase_restaurant_id', models.UUIDField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.JSONField(default=dict)),
                ('contact_info', models.JSONField(default=dict)),
                ('local_config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'restaurants',
                'indexes': [models.Index(fields=['supabase_restaurant_id', 'is_active'], name='restaurants_supabas_ae407f_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.restaurant')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_version', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, max_length=10)),
                ('module', models.CharField(choices=[('MENU_CACHE', 'Menu Cache'), ('ORDER_PROCESSING', 'Order Processing'), ('SYNC_MANAGER', 'Sync Manager'), ('OTP_SERVICE', 'OTP Service'), ('BILLING', 'Billing'), ('AUTH', 'Authentication'), ('CELERY', 'Celery Tasks')], db_index=True, max_length=20)),
                ('action', models.CharField(max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.restaurant')),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurant', '-created_at'], name='activity_lo_restaur_638819_idx'), models.Index(fields=['module', 'level', '-created_at'], name='activity_lo_module_39f3d8_idx'), models.Index(fields=['correlation_id'], name='activity_lo_correla_1e4f86_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_version', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_type', models.CharField(choices=[('ORDER_CREATE', 'Order Create'), ('ORDER_UPDATE', 'Order Update'), ('ORDER_DELETE', 'Order Delete'), ('MENU_UPDATE', 'Menu Update'), ('INVENTORY_UPDATE', 'Inventory Update')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CONFLICT', 'Conflict'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('priority', models.IntegerField(default=5)),
                ('payload', models.JSONField()),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('supabase_id', models.UUIDField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=5)),
                ('last_retry', models.DateTimeField(blank=True, null=True)),
                ('next_retry', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('conflict_data', models.JSONField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurant')),
            ],
            options={
                'db_table': 'sync_queue',
                'ordering': ['priority', 'created_at'],
                'indexes': [models.Index(fields=['restaurant', 'status', 'priority', 'created_at'], name='sync_queue_restaur_02ad61_idx'), models.Index(fields=['status', 'next_retry'], name='sync_queue_status_989d8c_idx'), models.Index(fields=['idempotency_key'], name='sync_queue_idempot_2f7982_idx')],
            },
        ),
    ]
