# Generated by Django 5.2.7 on 2025-11-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='module',
            field=models.CharField(choices=[('MENU_CACHE', 'Menu Cache'), ('ORDER_PROCESSING', 'Order Processing'), ('SYNC_MANAGER', 'Sync Manager'), ('OTP_SERVICE', 'OTP Service'), ('BILLING', 'Billing'), ('AUTH', 'Authentication'), ('CELERY', 'Celery Tasks'), ('PAYMENT', 'Payment Processing'), ('INVOICE', 'Invoice Management'), ('WALLET', 'Wallet Service'), ('ACCOUNTING', 'Accounting')], db_index=True, max_length=20),
        ),
    ]
