# Generated by Django 5.2.7 on 2025-11-30 06:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_activitylog_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'Restaurant', 'verbose_name_plural': 'Restaurants'},
        ),
        migrations.CreateModel(
            name='RestaurantCryptoAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('SUI', 'Sui'), ('SOL', 'Solana')], help_text='The specific cryptocurrency for this address.', max_length=5)),
                ('address', models.CharField(help_text='The public wallet address for receiving funds.', max_length=255)),
                ('network_config', models.JSONField(blank=True, default=dict, null=True)),
                ('restaurant', models.ForeignKey(help_text='The restaurant that owns this wallet address.', on_delete=django.db.models.deletion.CASCADE, related_name='crypto_addresses', to='core.restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant Crypto Address',
                'db_table': 'restaurant_crypto_addresses',
                'indexes': [models.Index(fields=['restaurant', 'currency'], name='restaurant__restaur_c3dda6_idx')],
                'unique_together': {('restaurant', 'currency')},
            },
        ),
    ]
